### ISSUE TITLE
dependency specified to rails_admin (>- 1.0.0) so bundle refuses to download for rails_admin 2.0

### ISSUE THREAD

**Issue by corneliusjaeger** [jemcode/rails_admin_actiontext#2]
Bundler could not find compatible versions for gem "rails_admin":
  In Gemfile:
    rails_admin (~> 2.0)

    rails_admin_actiontext was resolved to 0.0.2, which depends on
      rails_admin (>= 1.0.0, ~> 1.0)

Could this be corrected please?

**Comment by rikkipitt** [comment]
Hey @corneliusjaeger!

I've just tweaked the gemspec to be a bit more forgiving on the `rails_admin` dependency front. The latest version is now 0.0.3. Could you try and update this gem in your project and try to bundle again?

Let me know, thanks!

**Comment by corneliusjaeger** [comment]
Hi Rikki

Fixed for me, works as expected now. 
Thank you very much for the quick reply. And on a weekend no less.
Best
Cornelius

**Comment by rikkipitt** [comment]
You're welcome!

Closing this issue now. Cheers for reporting.
